#! /bin/sh

killall -q polybar; polybar &
killall -q sxhkd; sxhkd &

#removing x cursor
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6

bspc config normal_border_color \#FCA503
bspc config focused_border_color \#03FC03

# Padding from sides for more center-like look and overall better look 
bspc config top_padding             0 #73
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0

bspc config pointer_motion_interval 5
bspc config focus_follows_pointer   false
bspc config ignore_ewmh_focus       true
bspc config pointer_follows_monitor true
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config initial_polarity second_child
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
ibspc rule -a Screenkey manage=off
